//! Generated from the pinned upstream `internal/config/globals.go`.

pub const KNOWN_GLOBALS: &[&[&str]] = &[
    &["Array", "from"],
    &["Array", "fromAsync"],
    &["Array", "isArray"],
    &["Array", "of"],
    &["RegExp", "escape"],
    &["Map", "groupBy"],
    &["Object", "assign"],
    &["Object", "create"],
    &["Object", "defineProperties"],
    &["Object", "defineProperty"],
    &["Object", "entries"],
    &["Object", "freeze"],
    &["Object", "fromEntries"],
    &["Object", "getOwnPropertyDescriptor"],
    &["Object", "getOwnPropertyDescriptors"],
    &["Object", "getOwnPropertyNames"],
    &["Object", "getOwnPropertySymbols"],
    &["Object", "getPrototypeOf"],
    &["Object", "is"],
    &["Object", "isExtensible"],
    &["Object", "isFrozen"],
    &["Object", "isSealed"],
    &["Object", "keys"],
    &["Object", "preventExtensions"],
    &["Object", "seal"],
    &["Object", "setPrototypeOf"],
    &["Object", "values"],
    &["Object", "prototype", "__defineGetter__"],
    &["Object", "prototype", "__defineSetter__"],
    &["Object", "prototype", "__lookupGetter__"],
    &["Object", "prototype", "__lookupSetter__"],
    &["Object", "prototype", "hasOwnProperty"],
    &["Object", "prototype", "isPrototypeOf"],
    &["Object", "prototype", "propertyIsEnumerable"],
    &["Object", "prototype", "toLocaleString"],
    &["Object", "prototype", "toString"],
    &["Object", "prototype", "unwatch"],
    &["Object", "prototype", "valueOf"],
    &["Object", "prototype", "watch"],
    &["Symbol", "asyncDispose"],
    &["Symbol", "asyncIterator"],
    &["Symbol", "dispose"],
    &["Symbol", "hasInstance"],
    &["Symbol", "isConcatSpreadable"],
    &["Symbol", "iterator"],
    &["Symbol", "match"],
    &["Symbol", "matchAll"],
    &["Symbol", "replace"],
    &["Symbol", "search"],
    &["Symbol", "species"],
    &["Symbol", "split"],
    &["Symbol", "toPrimitive"],
    &["Symbol", "toStringTag"],
    &["Symbol", "unscopables"],
    &["Math", "E"],
    &["Math", "LN10"],
    &["Math", "LN2"],
    &["Math", "LOG10E"],
    &["Math", "LOG2E"],
    &["Math", "PI"],
    &["Math", "SQRT1_2"],
    &["Math", "SQRT2"],
    &["Math", "abs"],
    &["Math", "acos"],
    &["Math", "acosh"],
    &["Math", "asin"],
    &["Math", "asinh"],
    &["Math", "atan"],
    &["Math", "atan2"],
    &["Math", "atanh"],
    &["Math", "cbrt"],
    &["Math", "ceil"],
    &["Math", "clz32"],
    &["Math", "cos"],
    &["Math", "cosh"],
    &["Math", "exp"],
    &["Math", "expm1"],
    &["Math", "floor"],
    &["Math", "fround"],
    &["Math", "hypot"],
    &["Math", "imul"],
    &["Math", "log"],
    &["Math", "log10"],
    &["Math", "log1p"],
    &["Math", "log2"],
    &["Math", "max"],
    &["Math", "min"],
    &["Math", "pow"],
    &["Math", "random"],
    &["Math", "round"],
    &["Math", "sign"],
    &["Math", "sin"],
    &["Math", "sinh"],
    &["Math", "sqrt"],
    &["Math", "tan"],
    &["Math", "tanh"],
    &["Math", "trunc"],
    &["Reflect", "apply"],
    &["Reflect", "construct"],
    &["Reflect", "defineProperty"],
    &["Reflect", "deleteProperty"],
    &["Reflect", "get"],
    &["Reflect", "getOwnPropertyDescriptor"],
    &["Reflect", "getPrototypeOf"],
    &["Reflect", "has"],
    &["Reflect", "isExtensible"],
    &["Reflect", "ownKeys"],
    &["Reflect", "preventExtensions"],
    &["Reflect", "set"],
    &["Reflect", "setPrototypeOf"],
    &["JSON", "parse"],
    &["JSON", "stringify"],
    &["BigInt64Array", "from"],
    &["BigInt64Array", "of"],
    &["BigUint64Array", "from"],
    &["BigUint64Array", "of"],
    &["Float16Array", "from"],
    &["Float16Array", "of"],
    &["Float32Array", "from"],
    &["Float32Array", "of"],
    &["Float64Array", "from"],
    &["Float64Array", "of"],
    &["Int16Array", "from"],
    &["Int16Array", "of"],
    &["Int32Array", "from"],
    &["Int32Array", "of"],
    &["Int8Array", "from"],
    &["Int8Array", "of"],
    &["Uint16Array", "from"],
    &["Uint16Array", "of"],
    &["Uint32Array", "from"],
    &["Uint32Array", "of"],
    &["Uint8Array", "from"],
    &["Uint8Array", "fromBase64"],
    &["Uint8Array", "fromHex"],
    &["Uint8Array", "of"],
    &["Uint8ClampedArray", "from"],
    &["Uint8ClampedArray", "of"],
    &["AbortController"],
    &["AbortSignal"],
    &["AggregateError"],
    &["Array"],
    &["ArrayBuffer"],
    &["Atomics"],
    &["BigInt"],
    &["BigInt64Array"],
    &["BigUint64Array"],
    &["Boolean"],
    &["DataView"],
    &["Date"],
    &["Error"],
    &["EvalError"],
    &["Event"],
    &["EventTarget"],
    &["FinalizationRegistry"],
    &["Float16Array"],
    &["Float32Array"],
    &["Float64Array"],
    &["Function"],
    &["Int16Array"],
    &["Int32Array"],
    &["Int8Array"],
    &["Intl"],
    &["Iterator"],
    &["JSON"],
    &["Map"],
    &["Math"],
    &["MessageChannel"],
    &["MessageEvent"],
    &["MessagePort"],
    &["Number"],
    &["Object"],
    &["Promise"],
    &["Proxy"],
    &["RangeError"],
    &["ReferenceError"],
    &["Reflect"],
    &["RegExp"],
    &["Set"],
    &["SharedArrayBuffer"],
    &["String"],
    &["Symbol"],
    &["SyntaxError"],
    &["TextDecoder"],
    &["TextEncoder"],
    &["TypeError"],
    &["URIError"],
    &["URL"],
    &["URLSearchParams"],
    &["Uint16Array"],
    &["Uint32Array"],
    &["Uint8Array"],
    &["Uint8ClampedArray"],
    &["WeakMap"],
    &["WeakRef"],
    &["WeakSet"],
    &["WebAssembly"],
    &["clearInterval"],
    &["clearTimeout"],
    &["console"],
    &["decodeURI"],
    &["decodeURIComponent"],
    &["encodeURI"],
    &["encodeURIComponent"],
    &["escape"],
    &["globalThis"],
    &["isFinite"],
    &["isNaN"],
    &["parseFloat"],
    &["parseInt"],
    &["queueMicrotask"],
    &["setInterval"],
    &["setTimeout"],
    &["unescape"],
    &["console", "assert"],
    &["console", "clear"],
    &["console", "count"],
    &["console", "countReset"],
    &["console", "debug"],
    &["console", "dir"],
    &["console", "dirxml"],
    &["console", "error"],
    &["console", "group"],
    &["console", "groupCollapsed"],
    &["console", "groupEnd"],
    &["console", "info"],
    &["console", "log"],
    &["console", "table"],
    &["console", "time"],
    &["console", "timeEnd"],
    &["console", "timeLog"],
    &["console", "trace"],
    &["console", "warn"],
    &["CSSAnimation"],
    &["CSSFontFaceRule"],
    &["CSSImportRule"],
    &["CSSKeyframeRule"],
    &["CSSKeyframesRule"],
    &["CSSMediaRule"],
    &["CSSNamespaceRule"],
    &["CSSPageRule"],
    &["CSSRule"],
    &["CSSRuleList"],
    &["CSSStyleDeclaration"],
    &["CSSStyleRule"],
    &["CSSStyleSheet"],
    &["CSSSupportsRule"],
    &["CSSTransition"],
    &["SVGAElement"],
    &["SVGAngle"],
    &["SVGAnimateElement"],
    &["SVGAnimateMotionElement"],
    &["SVGAnimateTransformElement"],
    &["SVGAnimatedAngle"],
    &["SVGAnimatedBoolean"],
    &["SVGAnimatedEnumeration"],
    &["SVGAnimatedInteger"],
    &["SVGAnimatedLength"],
    &["SVGAnimatedLengthList"],
    &["SVGAnimatedNumber"],
    &["SVGAnimatedNumberList"],
    &["SVGAnimatedPreserveAspectRatio"],
    &["SVGAnimatedRect"],
    &["SVGAnimatedString"],
    &["SVGAnimatedTransformList"],
    &["SVGAnimationElement"],
    &["SVGCircleElement"],
    &["SVGClipPathElement"],
    &["SVGComponentTransferFunctionElement"],
    &["SVGDefsElement"],
    &["SVGDescElement"],
    &["SVGElement"],
    &["SVGEllipseElement"],
    &["SVGFEBlendElement"],
    &["SVGFEColorMatrixElement"],
    &["SVGFEComponentTransferElement"],
    &["SVGFECompositeElement"],
    &["SVGFEConvolveMatrixElement"],
    &["SVGFEDiffuseLightingElement"],
    &["SVGFEDisplacementMapElement"],
    &["SVGFEDistantLightElement"],
    &["SVGFEDropShadowElement"],
    &["SVGFEFloodElement"],
    &["SVGFEFuncAElement"],
    &["SVGFEFuncBElement"],
    &["SVGFEFuncGElement"],
    &["SVGFEFuncRElement"],
    &["SVGFEGaussianBlurElement"],
    &["SVGFEImageElement"],
    &["SVGFEMergeElement"],
    &["SVGFEMergeNodeElement"],
    &["SVGFEMorphologyElement"],
    &["SVGFEOffsetElement"],
    &["SVGFEPointLightElement"],
    &["SVGFESpecularLightingElement"],
    &["SVGFESpotLightElement"],
    &["SVGFETileElement"],
    &["SVGFETurbulenceElement"],
    &["SVGFilterElement"],
    &["SVGForeignObjectElement"],
    &["SVGGElement"],
    &["SVGGeometryElement"],
    &["SVGGradientElement"],
    &["SVGGraphicsElement"],
    &["SVGImageElement"],
    &["SVGLength"],
    &["SVGLengthList"],
    &["SVGLineElement"],
    &["SVGLinearGradientElement"],
    &["SVGMPathElement"],
    &["SVGMarkerElement"],
    &["SVGMaskElement"],
    &["SVGMatrix"],
    &["SVGMetadataElement"],
    &["SVGNumber"],
    &["SVGNumberList"],
    &["SVGPathElement"],
    &["SVGPatternElement"],
    &["SVGPoint"],
    &["SVGPointList"],
    &["SVGPolygonElement"],
    &["SVGPolylineElement"],
    &["SVGPreserveAspectRatio"],
    &["SVGRadialGradientElement"],
    &["SVGRect"],
    &["SVGRectElement"],
    &["SVGSVGElement"],
    &["SVGScriptElement"],
    &["SVGSetElement"],
    &["SVGStopElement"],
    &["SVGStringList"],
    &["SVGStyleElement"],
    &["SVGSwitchElement"],
    &["SVGSymbolElement"],
    &["SVGTSpanElement"],
    &["SVGTextContentElement"],
    &["SVGTextElement"],
    &["SVGTextPathElement"],
    &["SVGTextPositioningElement"],
    &["SVGTitleElement"],
    &["SVGTransform"],
    &["SVGTransformList"],
    &["SVGUnitTypes"],
    &["SVGUseElement"],
    &["SVGViewElement"],
    &["AnalyserNode"],
    &["Animation"],
    &["AnimationEffect"],
    &["AnimationEvent"],
    &["AnimationPlaybackEvent"],
    &["AnimationTimeline"],
    &["Attr"],
    &["Audio"],
    &["AudioBuffer"],
    &["AudioBufferSourceNode"],
    &["AudioDestinationNode"],
    &["AudioListener"],
    &["AudioNode"],
    &["AudioParam"],
    &["AudioProcessingEvent"],
    &["AudioScheduledSourceNode"],
    &["BarProp"],
    &["BeforeUnloadEvent"],
    &["BiquadFilterNode"],
    &["Blob"],
    &["BlobEvent"],
    &["ByteLengthQueuingStrategy"],
    &["CDATASection"],
    &["CSS"],
    &["CanvasGradient"],
    &["CanvasPattern"],
    &["CanvasRenderingContext2D"],
    &["ChannelMergerNode"],
    &["ChannelSplitterNode"],
    &["CharacterData"],
    &["ClipboardEvent"],
    &["CloseEvent"],
    &["Comment"],
    &["CompositionEvent"],
    &["ConvolverNode"],
    &["CountQueuingStrategy"],
    &["Crypto"],
    &["CustomElementRegistry"],
    &["CustomEvent"],
    &["DOMException"],
    &["DOMImplementation"],
    &["DOMMatrix"],
    &["DOMMatrixReadOnly"],
    &["DOMParser"],
    &["DOMPoint"],
    &["DOMPointReadOnly"],
    &["DOMQuad"],
    &["DOMRect"],
    &["DOMRectList"],
    &["DOMRectReadOnly"],
    &["DOMStringList"],
    &["DOMStringMap"],
    &["DOMTokenList"],
    &["DataTransfer"],
    &["DataTransferItem"],
    &["DataTransferItemList"],
    &["DelayNode"],
    &["Document"],
    &["DocumentFragment"],
    &["DocumentTimeline"],
    &["DocumentType"],
    &["DragEvent"],
    &["DynamicsCompressorNode"],
    &["Element"],
    &["ErrorEvent"],
    &["EventSource"],
    &["File"],
    &["FileList"],
    &["FileReader"],
    &["FocusEvent"],
    &["FontFace"],
    &["FormData"],
    &["GainNode"],
    &["Gamepad"],
    &["GamepadButton"],
    &["GamepadEvent"],
    &["Geolocation"],
    &["GeolocationPositionError"],
    &["HTMLAllCollection"],
    &["HTMLAnchorElement"],
    &["HTMLAreaElement"],
    &["HTMLAudioElement"],
    &["HTMLBRElement"],
    &["HTMLBaseElement"],
    &["HTMLBodyElement"],
    &["HTMLButtonElement"],
    &["HTMLCanvasElement"],
    &["HTMLCollection"],
    &["HTMLDListElement"],
    &["HTMLDataElement"],
    &["HTMLDataListElement"],
    &["HTMLDetailsElement"],
    &["HTMLDirectoryElement"],
    &["HTMLDivElement"],
    &["HTMLDocument"],
    &["HTMLElement"],
    &["HTMLEmbedElement"],
    &["HTMLFieldSetElement"],
    &["HTMLFontElement"],
    &["HTMLFormControlsCollection"],
    &["HTMLFormElement"],
    &["HTMLFrameElement"],
    &["HTMLFrameSetElement"],
    &["HTMLHRElement"],
    &["HTMLHeadElement"],
    &["HTMLHeadingElement"],
    &["HTMLHtmlElement"],
    &["HTMLIFrameElement"],
    &["HTMLImageElement"],
    &["HTMLInputElement"],
    &["HTMLLIElement"],
    &["HTMLLabelElement"],
    &["HTMLLegendElement"],
    &["HTMLLinkElement"],
    &["HTMLMapElement"],
    &["HTMLMarqueeElement"],
    &["HTMLMediaElement"],
    &["HTMLMenuElement"],
    &["HTMLMetaElement"],
    &["HTMLMeterElement"],
    &["HTMLModElement"],
    &["HTMLOListElement"],
    &["HTMLObjectElement"],
    &["HTMLOptGroupElement"],
    &["HTMLOptionElement"],
    &["HTMLOptionsCollection"],
    &["HTMLOutputElement"],
    &["HTMLParagraphElement"],
    &["HTMLParamElement"],
    &["HTMLPictureElement"],
    &["HTMLPreElement"],
    &["HTMLProgressElement"],
    &["HTMLQuoteElement"],
    &["HTMLScriptElement"],
    &["HTMLSelectElement"],
    &["HTMLSlotElement"],
    &["HTMLSourceElement"],
    &["HTMLSpanElement"],
    &["HTMLStyleElement"],
    &["HTMLTableCaptionElement"],
    &["HTMLTableCellElement"],
    &["HTMLTableColElement"],
    &["HTMLTableElement"],
    &["HTMLTableRowElement"],
    &["HTMLTableSectionElement"],
    &["HTMLTemplateElement"],
    &["HTMLTextAreaElement"],
    &["HTMLTimeElement"],
    &["HTMLTitleElement"],
    &["HTMLTrackElement"],
    &["HTMLUListElement"],
    &["HTMLUnknownElement"],
    &["HTMLVideoElement"],
    &["HashChangeEvent"],
    &["Headers"],
    &["History"],
    &["IDBCursor"],
    &["IDBCursorWithValue"],
    &["IDBDatabase"],
    &["IDBFactory"],
    &["IDBIndex"],
    &["IDBKeyRange"],
    &["IDBObjectStore"],
    &["IDBOpenDBRequest"],
    &["IDBRequest"],
    &["IDBTransaction"],
    &["IDBVersionChangeEvent"],
    &["Image"],
    &["ImageData"],
    &["InputEvent"],
    &["IntersectionObserver"],
    &["IntersectionObserverEntry"],
    &["KeyboardEvent"],
    &["KeyframeEffect"],
    &["Location"],
    &["MediaCapabilities"],
    &["MediaElementAudioSourceNode"],
    &["MediaEncryptedEvent"],
    &["MediaError"],
    &["MediaList"],
    &["MediaQueryList"],
    &["MediaQueryListEvent"],
    &["MediaRecorder"],
    &["MediaSource"],
    &["MediaStream"],
    &["MediaStreamAudioDestinationNode"],
    &["MediaStreamAudioSourceNode"],
    &["MediaStreamTrack"],
    &["MediaStreamTrackEvent"],
    &["MimeType"],
    &["MimeTypeArray"],
    &["MouseEvent"],
    &["MutationEvent"],
    &["MutationObserver"],
    &["MutationRecord"],
    &["NamedNodeMap"],
    &["Navigator"],
    &["Node"],
    &["NodeFilter"],
    &["NodeIterator"],
    &["NodeList"],
    &["Notification"],
    &["OfflineAudioCompletionEvent"],
    &["Option"],
    &["OscillatorNode"],
    &["PageTransitionEvent"],
    &["Path2D"],
    &["Performance"],
    &["PerformanceEntry"],
    &["PerformanceMark"],
    &["PerformanceMeasure"],
    &["PerformanceNavigation"],
    &["PerformanceObserver"],
    &["PerformanceObserverEntryList"],
    &["PerformanceResourceTiming"],
    &["PerformanceTiming"],
    &["PeriodicWave"],
    &["Plugin"],
    &["PluginArray"],
    &["PointerEvent"],
    &["PopStateEvent"],
    &["ProcessingInstruction"],
    &["ProgressEvent"],
    &["PromiseRejectionEvent"],
    &["RTCCertificate"],
    &["RTCDTMFSender"],
    &["RTCDTMFToneChangeEvent"],
    &["RTCDataChannel"],
    &["RTCDataChannelEvent"],
    &["RTCIceCandidate"],
    &["RTCPeerConnection"],
    &["RTCPeerConnectionIceEvent"],
    &["RTCRtpReceiver"],
    &["RTCRtpSender"],
    &["RTCRtpTransceiver"],
    &["RTCSessionDescription"],
    &["RTCStatsReport"],
    &["RTCTrackEvent"],
    &["RadioNodeList"],
    &["Range"],
    &["ReadableStream"],
    &["Request"],
    &["ResizeObserver"],
    &["ResizeObserverEntry"],
    &["Response"],
    &["Screen"],
    &["ScriptProcessorNode"],
    &["SecurityPolicyViolationEvent"],
    &["Selection"],
    &["ShadowRoot"],
    &["SourceBuffer"],
    &["SourceBufferList"],
    &["SpeechSynthesisEvent"],
    &["SpeechSynthesisUtterance"],
    &["StaticRange"],
    &["Storage"],
    &["StorageEvent"],
    &["StyleSheet"],
    &["StyleSheetList"],
    &["Text"],
    &["TextMetrics"],
    &["TextTrack"],
    &["TextTrackCue"],
    &["TextTrackCueList"],
    &["TextTrackList"],
    &["TimeRanges"],
    &["TrackEvent"],
    &["TransitionEvent"],
    &["TreeWalker"],
    &["UIEvent"],
    &["VTTCue"],
    &["ValidityState"],
    &["VisualViewport"],
    &["WaveShaperNode"],
    &["WebGLActiveInfo"],
    &["WebGLBuffer"],
    &["WebGLContextEvent"],
    &["WebGLFramebuffer"],
    &["WebGLProgram"],
    &["WebGLQuery"],
    &["WebGLRenderbuffer"],
    &["WebGLRenderingContext"],
    &["WebGLSampler"],
    &["WebGLShader"],
    &["WebGLShaderPrecisionFormat"],
    &["WebGLSync"],
    &["WebGLTexture"],
    &["WebGLUniformLocation"],
    &["WebKitCSSMatrix"],
    &["WebSocket"],
    &["WheelEvent"],
    &["Window"],
    &["Worker"],
    &["XMLDocument"],
    &["XMLHttpRequest"],
    &["XMLHttpRequestEventTarget"],
    &["XMLHttpRequestUpload"],
    &["XMLSerializer"],
    &["XPathEvaluator"],
    &["XPathExpression"],
    &["XPathResult"],
    &["XSLTProcessor"],
    &["alert"],
    &["atob"],
    &["blur"],
    &["btoa"],
    &["cancelAnimationFrame"],
    &["captureEvents"],
    &["close"],
    &["closed"],
    &["confirm"],
    &["customElements"],
    &["devicePixelRatio"],
    &["document"],
    &["event"],
    &["fetch"],
    &["find"],
    &["focus"],
    &["frameElement"],
    &["frames"],
    &["getComputedStyle"],
    &["getSelection"],
    &["history"],
    &["indexedDB"],
    &["isSecureContext"],
    &["length"],
    &["location"],
    &["locationbar"],
    &["matchMedia"],
    &["menubar"],
    &["moveBy"],
    &["moveTo"],
    &["name"],
    &["navigator"],
    &["onabort"],
    &["onafterprint"],
    &["onanimationend"],
    &["onanimationiteration"],
    &["onanimationstart"],
    &["onbeforeprint"],
    &["onbeforeunload"],
    &["onblur"],
    &["oncanplay"],
    &["oncanplaythrough"],
    &["onchange"],
    &["onclick"],
    &["oncontextmenu"],
    &["oncuechange"],
    &["ondblclick"],
    &["ondrag"],
    &["ondragend"],
    &["ondragenter"],
    &["ondragleave"],
    &["ondragover"],
    &["ondragstart"],
    &["ondrop"],
    &["ondurationchange"],
    &["onemptied"],
    &["onended"],
    &["onerror"],
    &["onfocus"],
    &["ongotpointercapture"],
    &["onhashchange"],
    &["oninput"],
    &["oninvalid"],
    &["onkeydown"],
    &["onkeypress"],
    &["onkeyup"],
    &["onlanguagechange"],
    &["onload"],
    &["onloadeddata"],
    &["onloadedmetadata"],
    &["onloadstart"],
    &["onlostpointercapture"],
    &["onmessage"],
    &["onmousedown"],
    &["onmouseenter"],
    &["onmouseleave"],
    &["onmousemove"],
    &["onmouseout"],
    &["onmouseover"],
    &["onmouseup"],
    &["onoffline"],
    &["ononline"],
    &["onpagehide"],
    &["onpageshow"],
    &["onpause"],
    &["onplay"],
    &["onplaying"],
    &["onpointercancel"],
    &["onpointerdown"],
    &["onpointerenter"],
    &["onpointerleave"],
    &["onpointermove"],
    &["onpointerout"],
    &["onpointerover"],
    &["onpointerup"],
    &["onpopstate"],
    &["onprogress"],
    &["onratechange"],
    &["onrejectionhandled"],
    &["onreset"],
    &["onresize"],
    &["onscroll"],
    &["onseeked"],
    &["onseeking"],
    &["onselect"],
    &["onstalled"],
    &["onstorage"],
    &["onsubmit"],
    &["onsuspend"],
    &["ontimeupdate"],
    &["ontoggle"],
    &["ontransitioncancel"],
    &["ontransitionend"],
    &["ontransitionrun"],
    &["ontransitionstart"],
    &["onunhandledrejection"],
    &["onunload"],
    &["onvolumechange"],
    &["onwaiting"],
    &["onwebkitanimationend"],
    &["onwebkitanimationiteration"],
    &["onwebkitanimationstart"],
    &["onwebkittransitionend"],
    &["onwheel"],
    &["open"],
    &["opener"],
    &["origin"],
    &["outerHeight"],
    &["outerWidth"],
    &["parent"],
    &["performance"],
    &["personalbar"],
    &["postMessage"],
    &["print"],
    &["prompt"],
    &["releaseEvents"],
    &["requestAnimationFrame"],
    &["resizeBy"],
    &["resizeTo"],
    &["screen"],
    &["screenLeft"],
    &["screenTop"],
    &["screenX"],
    &["screenY"],
    &["scroll"],
    &["scrollBy"],
    &["scrollTo"],
    &["scrollbars"],
    &["self"],
    &["speechSynthesis"],
    &["status"],
    &["statusbar"],
    &["stop"],
    &["toolbar"],
    &["top"],
    &["webkitURL"],
    &["window"],
];
