// Generated from upstream internal/compat/js_table.go.

use super::{Engine, FeatureTable, JsFeature, VersionRange};

pub(super) const JS_TABLE: FeatureTable = &[
    (
        JsFeature::ARBITRARY_MODULE_NAMESPACE_NAMES,
        &[
            (Engine::Chrome, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(87, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 5, 0)]),
            (Engine::Node, &[VersionRange::from_start(16, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 1, 0)]),
        ],
    ),
    (
        JsFeature::ARRAY_SPREAD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(46, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(13, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(36, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(5, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(33, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::ARROW,
        &[
            (Engine::Chrome, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(13, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(45, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(36, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::ASYNC_AWAIT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(55, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2017, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(52, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(11, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(7, 6, 0)]),
            (Engine::Opera, &[VersionRange::from_start(42, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(11, 0, 0)]),
        ],
    ),
    (
        JsFeature::ASYNC_GENERATOR,
        &[
            (Engine::Chrome, &[VersionRange::from_start(63, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2018, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(57, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(50, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(12, 0, 0)]),
        ],
    ),
    (
        JsFeature::BIGINT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(67, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2020, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(68, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 12, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(10, 4, 0)]),
            (Engine::Opera, &[VersionRange::from_start(54, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 7, 14)]),
            (Engine::Safari, &[VersionRange::from_start(14, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(13, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(45, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(36, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_FIELD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(73, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(69, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(60, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_PRIVATE_ACCESSOR,
        &[
            (Engine::Chrome, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(14, 6, 0)]),
            (Engine::Opera, &[VersionRange::from_start(70, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(15, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_PRIVATE_BRAND_CHECK,
        &[
            (Engine::Chrome, &[VersionRange::from_start(91, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 9, 0)]),
            (Engine::Edge, &[VersionRange::from_start(91, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(16, 9, 0)]),
            (Engine::Opera, &[VersionRange::from_start(77, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(15, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_PRIVATE_FIELD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 5, 0)]),
            (Engine::Node, &[VersionRange::from_start(14, 6, 0)]),
            (Engine::Opera, &[VersionRange::from_start(70, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 1, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_PRIVATE_METHOD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(14, 6, 0)]),
            (Engine::Opera, &[VersionRange::from_start(70, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(15, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_PRIVATE_STATIC_ACCESSOR,
        &[
            (Engine::Chrome, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(14, 6, 0)]),
            (Engine::Opera, &[VersionRange::from_start(70, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(15, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_PRIVATE_STATIC_FIELD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(74, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 5, 0)]),
            (Engine::Node, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(62, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 1, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_PRIVATE_STATIC_METHOD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(84, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(14, 6, 0)]),
            (Engine::Opera, &[VersionRange::from_start(70, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(15, 0, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_STATIC_BLOCKS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(91, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 14, 0)]),
            (Engine::Edge, &[VersionRange::from_start(94, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(93, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(16, 4, 0)]),
            (Engine::Node, &[VersionRange::from_start(16, 11, 0)]),
            (Engine::Opera, &[VersionRange::from_start(80, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(16, 4, 0)]),
        ],
    ),
    (
        JsFeature::CLASS_STATIC_FIELD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(73, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(75, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 5, 0)]),
            (Engine::Node, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(60, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 1, 0)]),
        ],
    ),
    (
        JsFeature::CONST_AND_LET,
        &[
            (Engine::Chrome, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(51, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(11, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(36, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(11, 0, 0)]),
        ],
    ),
    (JsFeature::DECORATORS, &[]),
    (
        JsFeature::DEFAULT_ARGUMENT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(53, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(36, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::DESTRUCTURING,
        &[
            (Engine::Chrome, &[VersionRange::from_start(51, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(18, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(53, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 5, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 5, 0)]),
            (Engine::Opera, &[VersionRange::from_start(38, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 1, 0)]),
        ],
    ),
    (
        JsFeature::DYNAMIC_IMPORT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(63, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(67, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(11, 0, 0)]),
            (
                Engine::Node,
                &[
                    VersionRange::bounded(12, 20, 0, 13, 0, 0),
                    VersionRange::from_start(13, 2, 0),
                ],
            ),
            (Engine::Opera, &[VersionRange::from_start(50, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(11, 1, 0)]),
        ],
    ),
    (
        JsFeature::EXPONENT_OPERATOR,
        &[
            (Engine::Chrome, &[VersionRange::from_start(52, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2016, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(52, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 3, 0)]),
            (Engine::Node, &[VersionRange::from_start(7, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(39, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 7, 14)]),
            (Engine::Safari, &[VersionRange::from_start(10, 1, 0)]),
        ],
    ),
    (
        JsFeature::EXPORT_STAR_AS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(72, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2020, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(80, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 5, 0)]),
            (Engine::Node, &[VersionRange::from_start(13, 2, 0)]),
            (Engine::Opera, &[VersionRange::from_start(60, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 1, 0)]),
        ],
    ),
    (
        JsFeature::FOR_AWAIT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(63, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2018, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(57, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(50, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(12, 0, 0)]),
        ],
    ),
    (
        JsFeature::FOR_OF,
        &[
            (Engine::Chrome, &[VersionRange::from_start(51, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(53, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 5, 0)]),
            (Engine::Opera, &[VersionRange::from_start(38, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::FROM_BASE64,
        &[
            (Engine::Chrome, &[VersionRange::from_start(140, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(2, 5, 0)]),
            (Engine::Edge, &[VersionRange::from_start(140, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(133, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(18, 2, 0)]),
            (Engine::Node, &[VersionRange::from_start(25, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(124, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(18, 2, 0)]),
        ],
    ),
    (
        JsFeature::FUNCTION_NAME_CONFIGURABLE,
        &[
            (Engine::Chrome, &[VersionRange::from_start(43, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(38, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(4, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(30, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 7, 15)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::FUNCTION_OR_CLASS_PROPERTY_ACCESS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Ie, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(16, 3, 0)]),
        ],
    ),
    (
        JsFeature::GENERATOR,
        &[
            (Engine::Chrome, &[VersionRange::from_start(50, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(13, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(53, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(37, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::HASHBANG,
        &[
            (Engine::Chrome, &[VersionRange::from_start(74, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2023, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(67, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(13, 4, 0)]),
            (Engine::Node, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(62, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 7, 15)]),
            (Engine::Safari, &[VersionRange::from_start(13, 1, 0)]),
        ],
    ),
    (
        JsFeature::IMPORT_ASSERTIONS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(91, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 17, 0)]),
            (Engine::Edge, &[VersionRange::from_start(91, 0, 0)]),
            (Engine::Node, &[VersionRange::bounded(16, 14, 0, 22, 0, 0)]),
        ],
    ),
    (
        JsFeature::IMPORT_ATTRIBUTES,
        &[
            (Engine::Chrome, &[VersionRange::from_start(123, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 37, 0)]),
            (Engine::Edge, &[VersionRange::from_start(123, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(138, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(17, 2, 0)]),
            (
                Engine::Node,
                &[
                    VersionRange::bounded(18, 20, 0, 19, 0, 0),
                    VersionRange::from_start(20, 10, 0),
                ],
            ),
            (Engine::Opera, &[VersionRange::from_start(109, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(17, 2, 0)]),
        ],
    ),
    (JsFeature::IMPORT_DEFER, &[]),
    (
        JsFeature::IMPORT_META,
        &[
            (Engine::Chrome, &[VersionRange::from_start(64, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2020, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(62, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(10, 4, 0)]),
            (Engine::Opera, &[VersionRange::from_start(51, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(11, 1, 0)]),
        ],
    ),
    (JsFeature::IMPORT_SOURCE, &[]),
    (JsFeature::INLINE_SCRIPT, &[]),
    (
        JsFeature::LOGICAL_ASSIGNMENT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(85, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 2, 0)]),
            (Engine::Edge, &[VersionRange::from_start(85, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2021, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(71, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(14, 0, 0)]),
        ],
    ),
    (
        JsFeature::NESTED_REST_BINDING,
        &[
            (Engine::Chrome, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2016, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(47, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 3, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(36, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 1, 0)]),
        ],
    ),
    (
        JsFeature::NEW_TARGET,
        &[
            (Engine::Chrome, &[VersionRange::from_start(46, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(41, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(5, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(33, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::NODE_COLON_PREFIX_IMPORT,
        &[
            (Engine::Es, &[VersionRange::from_start(0, 0, 0)]),
            (
                Engine::Node,
                &[
                    VersionRange::bounded(12, 20, 0, 13, 0, 0),
                    VersionRange::from_start(14, 13, 1),
                ],
            ),
        ],
    ),
    (
        JsFeature::NODE_COLON_PREFIX_REQUIRE,
        &[
            (Engine::Es, &[VersionRange::from_start(0, 0, 0)]),
            (
                Engine::Node,
                &[
                    VersionRange::bounded(14, 18, 0, 15, 0, 0),
                    VersionRange::from_start(16, 0, 0),
                ],
            ),
        ],
    ),
    (
        JsFeature::NULLISH_COALESCING,
        &[
            (Engine::Chrome, &[VersionRange::from_start(80, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(80, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2020, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(72, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(13, 4, 0)]),
            (Engine::Node, &[VersionRange::from_start(14, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(67, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 8, 0)]),
            (Engine::Safari, &[VersionRange::from_start(13, 1, 0)]),
        ],
    ),
    (
        JsFeature::OBJECT_ACCESSORS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(5, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(5, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(2, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ie, &[VersionRange::from_start(9, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(0, 4, 0)]),
            (Engine::Opera, &[VersionRange::from_start(10, 10, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 7, 13)]),
            (Engine::Safari, &[VersionRange::from_start(3, 1, 0)]),
        ],
    ),
    (
        JsFeature::OBJECT_EXTENSIONS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(44, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(34, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(4, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(31, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 8, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::OBJECT_REST_SPREAD,
        &[
            (Engine::Chrome, &[VersionRange::from_start(60, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2018, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(55, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(11, 3, 0)]),
            (Engine::Node, &[VersionRange::from_start(8, 3, 0)]),
            (Engine::Opera, &[VersionRange::from_start(47, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(11, 1, 0)]),
        ],
    ),
    (
        JsFeature::OPTIONAL_CATCH_BINDING,
        &[
            (Engine::Chrome, &[VersionRange::from_start(66, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2019, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(58, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 12, 0)]),
            (Engine::Ios, &[VersionRange::from_start(11, 3, 0)]),
            (Engine::Node, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(53, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(11, 1, 0)]),
        ],
    ),
    (
        JsFeature::OPTIONAL_CHAIN,
        &[
            (Engine::Chrome, &[VersionRange::from_start(91, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 9, 0)]),
            (Engine::Edge, &[VersionRange::from_start(91, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2020, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(74, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 12, 0)]),
            (Engine::Ios, &[VersionRange::from_start(13, 4, 0)]),
            (Engine::Node, &[VersionRange::from_start(16, 9, 0)]),
            (Engine::Opera, &[VersionRange::from_start(77, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(13, 1, 0)]),
        ],
    ),
    (
        JsFeature::REGEXP_DOT_ALL_FLAG,
        &[
            (Engine::Chrome, &[VersionRange::from_start(62, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2018, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(78, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(11, 3, 0)]),
            (Engine::Node, &[VersionRange::from_start(8, 10, 0)]),
            (Engine::Opera, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 7, 15)]),
            (Engine::Safari, &[VersionRange::from_start(11, 1, 0)]),
        ],
    ),
    (
        JsFeature::REGEXP_LOOKBEHIND_ASSERTIONS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(62, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2018, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(78, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(16, 4, 0)]),
            (Engine::Node, &[VersionRange::from_start(8, 10, 0)]),
            (Engine::Opera, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 9, 0)]),
            (Engine::Safari, &[VersionRange::from_start(16, 4, 0)]),
        ],
    ),
    (
        JsFeature::REGEXP_MATCH_INDICES,
        &[
            (Engine::Chrome, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 8, 0)]),
            (Engine::Edge, &[VersionRange::from_start(90, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(88, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(16, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(76, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(15, 0, 0)]),
        ],
    ),
    (
        JsFeature::REGEXP_NAMED_CAPTURE_GROUPS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(64, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2018, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(78, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(11, 3, 0)]),
            (Engine::Node, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(51, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 9, 0)]),
            (Engine::Safari, &[VersionRange::from_start(11, 1, 0)]),
        ],
    ),
    (
        JsFeature::REGEXP_SET_NOTATION,
        &[(Engine::Es, &[VersionRange::from_start(2024, 0, 0)])],
    ),
    (
        JsFeature::REGEXP_STICKY_AND_UNICODE_FLAGS,
        &[
            (Engine::Chrome, &[VersionRange::from_start(50, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(13, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(46, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(37, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(12, 0, 0)]),
        ],
    ),
    (
        JsFeature::REGEXP_UNICODE_PROPERTY_ESCAPES,
        &[
            (Engine::Es, &[VersionRange::from_start(2018, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(147, 0, 0)]),
        ],
    ),
    (
        JsFeature::REST_ARGUMENT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(47, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(43, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(10, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(6, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(34, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(10, 0, 0)]),
        ],
    ),
    (
        JsFeature::TEMPLATE_LITERAL,
        &[
            (Engine::Chrome, &[VersionRange::from_start(62, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(79, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(53, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(13, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(8, 10, 0)]),
            (Engine::Opera, &[VersionRange::from_start(49, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 9, 0)]),
            (Engine::Safari, &[VersionRange::from_start(13, 0, 0)]),
        ],
    ),
    (
        JsFeature::TOP_LEVEL_AWAIT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(89, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(89, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2022, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(89, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(15, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(14, 8, 0)]),
            (Engine::Opera, &[VersionRange::from_start(75, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(15, 0, 0)]),
        ],
    ),
    (
        JsFeature::TYPEOF_EXOTIC_OBJECT_IS_OBJECT,
        &[
            (Engine::Chrome, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2020, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Ios, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(0, 0, 0)]),
            (Engine::Safari, &[VersionRange::from_start(0, 0, 0)]),
        ],
    ),
    (
        JsFeature::UNICODE_ESCAPES,
        &[
            (Engine::Chrome, &[VersionRange::from_start(44, 0, 0)]),
            (Engine::Deno, &[VersionRange::from_start(1, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(12, 0, 0)]),
            (Engine::Es, &[VersionRange::from_start(2015, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(53, 0, 0)]),
            (Engine::Hermes, &[VersionRange::from_start(0, 7, 0)]),
            (Engine::Ios, &[VersionRange::from_start(9, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(4, 0, 0)]),
            (Engine::Opera, &[VersionRange::from_start(31, 0, 0)]),
            (Engine::Rhino, &[VersionRange::from_start(1, 7, 15)]),
            (Engine::Safari, &[VersionRange::from_start(9, 0, 0)]),
        ],
    ),
    (
        JsFeature::USING,
        &[
            (Engine::Chrome, &[VersionRange::from_start(141, 0, 0)]),
            (Engine::Edge, &[VersionRange::from_start(141, 0, 0)]),
            (Engine::Firefox, &[VersionRange::from_start(141, 0, 0)]),
            (Engine::Node, &[VersionRange::from_start(25, 0, 0)]),
        ],
    ),
];
