//! Native prerequisites exposed by unchanged service JS API assertions.

use esbuild_rs::{api, internal::xxhash};

#[test]
fn hash_matches_pinned_go_at_block_and_tail_boundaries() {
    // Generated by /tmp/esbuild-team-service-go-hash/main.go against the exact
    // UPSTREAM.md source, not by the Rust implementation under test.
    let vectors: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/service_xxhash_go_vectors.json")).unwrap();
    for vector in vectors.as_array().unwrap() {
        let length = usize::try_from(vector["length"].as_u64().unwrap()).unwrap();
        let expected = u64::from_str_radix(vector["hash_hex"].as_str().unwrap(), 16).unwrap();
        let bytes: Vec<u8> = (0_u8..=255).cycle().take(length).collect();
        assert_eq!(xxhash::sum64(&bytes), expected, "length={length}");
        for chunk_size in [1, 7, 31, 32, 33, 64] {
            let mut hash = xxhash::Digest::new();
            for chunk in bytes.chunks(chunk_size) {
                hash.write(chunk);
            }
            assert_eq!(
                hash.sum64(),
                expected,
                "length={length}, chunk={chunk_size}"
            );
        }
    }
}

#[test]
fn unrenamed_identifier_has_no_name_in_source_map() {
    let result = api::transform(
        "let       x",
        api::TransformOptions {
            sourcefile: "afile.js".into(),
            sourcemap: api::BuildSourceMap::External,
            ..api::TransformOptions::default()
        },
    );
    assert!(result.errors.is_empty());
    let map: serde_json::Value = serde_json::from_slice(&result.map).unwrap();
    assert_eq!(map["names"], serde_json::json!([]));
    assert_eq!(map["mappings"], "AAAA,IAAU;");
}

#[test]
fn minified_call_targets_keep_original_names_at_the_printed_identifier() {
    let result = api::transform(
        "function fn(callback){ callback(); callback.call(null) } fn(console.log);",
        api::TransformOptions {
            sourcefile: "intermediate.js".into(),
            sourcemap: api::BuildSourceMap::External,
            minify_whitespace: true,
            minify_identifiers: true,
            minify_syntax: true,
            ..api::TransformOptions::default()
        },
    );
    assert!(result.errors.is_empty());
    assert_eq!(
        result.code,
        b"function fn(n){n(),n.call(null)}fn(console.log);\n"
    );
    let map: serde_json::Value = serde_json::from_slice(&result.map).unwrap();
    assert_eq!(map["names"], serde_json::json!(["callback"]));
    assert_eq!(named_columns(&map), [(0, 12), (0, 15), (0, 19)]);
}

fn named_columns(map: &serde_json::Value) -> Vec<(usize, i32)> {
    let mut state = [0; 5];
    let mut named_columns = Vec::new();
    for (line, mappings) in map["mappings"].as_str().unwrap().split(';').enumerate() {
        state[0] = 0;
        for segment in mappings.split(',').filter(|segment| !segment.is_empty()) {
            let mut offset = 0;
            let mut count = 0;
            while offset < segment.len() {
                let (delta, next) =
                    esbuild_rs::internal::sourcemap::decode_vlq(segment.as_bytes(), offset);
                state[count] += delta;
                count += 1;
                offset = next;
            }
            if count == 5 {
                named_columns.push((line, state[0]));
            }
        }
    }
    named_columns
}

#[test]
fn renamed_postfix_values_keep_names_in_statements_and_return_expressions() {
    for (input, expected) in [
        (
            "function fn(argument){ argument++; return argument } fn(1)",
            vec![(0, 12), (1, 2), (2, 9)],
        ),
        (
            "function fn(argument){ return argument++ } fn(1)",
            vec![(0, 12), (1, 9)],
        ),
    ] {
        let result = api::transform(
            input,
            api::TransformOptions {
                minify_identifiers: true,
                sourcemap: api::BuildSourceMap::External,
                sourcefile: "intermediate.js".into(),
                ..api::TransformOptions::default()
            },
        );
        assert!(result.errors.is_empty());
        let map: serde_json::Value = serde_json::from_slice(&result.map).unwrap();
        assert_eq!(map["names"], serde_json::json!(["argument"]));
        assert_eq!(named_columns(&map), expected, "{input}");
    }
}

#[test]
fn relative_working_directory_uses_pinned_go_api_message() {
    let result = api::build(api::BuildOptions {
        abs_working_dir: "what is this? certainly not an absolute path".into(),
        ..api::BuildOptions::default()
    });
    assert_eq!(result.errors.len(), 1);
    assert_eq!(
        result.errors[0].text,
        "The working directory \"what is this? certainly not an absolute path\" is not an absolute path"
    );
}
