//! Generated from the pinned upstream `internal/js_lexer` tables.
#![allow(clippy::match_same_arms, clippy::too_many_lines)]

#[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum Token {
    #[default]
    EndOfFile,
    SyntaxError,
    Hashbang,
    NoSubstitutionTemplateLiteral,
    NumericLiteral,
    StringLiteral,
    BigIntegerLiteral,
    TemplateHead,
    TemplateMiddle,
    TemplateTail,
    Ampersand,
    AmpersandAmpersand,
    Asterisk,
    AsteriskAsterisk,
    At,
    Bar,
    BarBar,
    Caret,
    CloseBrace,
    CloseBracket,
    CloseParen,
    Colon,
    Comma,
    Dot,
    DotDotDot,
    EqualsEquals,
    EqualsEqualsEquals,
    EqualsGreaterThan,
    Exclamation,
    ExclamationEquals,
    ExclamationEqualsEquals,
    GreaterThan,
    GreaterThanEquals,
    GreaterThanGreaterThan,
    GreaterThanGreaterThanGreaterThan,
    LessThan,
    LessThanEquals,
    LessThanLessThan,
    Minus,
    MinusMinus,
    OpenBrace,
    OpenBracket,
    OpenParen,
    Percent,
    Plus,
    PlusPlus,
    Question,
    QuestionDot,
    QuestionQuestion,
    Semicolon,
    Slash,
    Tilde,
    AmpersandAmpersandEquals,
    AmpersandEquals,
    AsteriskAsteriskEquals,
    AsteriskEquals,
    BarBarEquals,
    BarEquals,
    CaretEquals,
    Equals,
    GreaterThanGreaterThanEquals,
    GreaterThanGreaterThanGreaterThanEquals,
    LessThanLessThanEquals,
    MinusEquals,
    PercentEquals,
    PlusEquals,
    QuestionQuestionEquals,
    SlashEquals,
    PrivateIdentifier,
    Identifier,
    EscapedKeyword,
    Break,
    Case,
    Catch,
    Class,
    Const,
    Continue,
    Debugger,
    Default,
    Delete,
    Do,
    Else,
    Enum,
    Export,
    Extends,
    False,
    Finally,
    For,
    Function,
    If,
    Import,
    In,
    Instanceof,
    New,
    Null,
    Return,
    Super,
    Switch,
    This,
    Throw,
    True,
    Try,
    Typeof,
    Var,
    Void,
    While,
    With,
}

pub type T = Token;

impl Token {
    #[must_use]
    pub const fn is_assign(self) -> bool {
        self as u8 >= Self::AmpersandAmpersandEquals as u8 && self as u8 <= Self::SlashEquals as u8
    }

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::EndOfFile => "end of file",
            Self::SyntaxError => "syntax error",
            Self::Hashbang => "hashbang comment",
            Self::NoSubstitutionTemplateLiteral => "template literal",
            Self::NumericLiteral => "number",
            Self::StringLiteral => "string",
            Self::BigIntegerLiteral => "bigint",
            Self::TemplateHead => "template literal",
            Self::TemplateMiddle => "template literal",
            Self::TemplateTail => "template literal",
            Self::Ampersand => "\"&\"",
            Self::AmpersandAmpersand => "\"&&\"",
            Self::Asterisk => "\"*\"",
            Self::AsteriskAsterisk => "\"**\"",
            Self::At => "\"@\"",
            Self::Bar => "\"|\"",
            Self::BarBar => "\"||\"",
            Self::Caret => "\"^\"",
            Self::CloseBrace => "\"}\"",
            Self::CloseBracket => "\"]\"",
            Self::CloseParen => "\")\"",
            Self::Colon => "\":\"",
            Self::Comma => "\",\"",
            Self::Dot => "\".\"",
            Self::DotDotDot => "\"...\"",
            Self::EqualsEquals => "\"==\"",
            Self::EqualsEqualsEquals => "\"===\"",
            Self::EqualsGreaterThan => "\"=>\"",
            Self::Exclamation => "\"!\"",
            Self::ExclamationEquals => "\"!=\"",
            Self::ExclamationEqualsEquals => "\"!==\"",
            Self::GreaterThan => "\">\"",
            Self::GreaterThanEquals => "\">=\"",
            Self::GreaterThanGreaterThan => "\">>\"",
            Self::GreaterThanGreaterThanGreaterThan => "\">>>\"",
            Self::LessThan => "\"<\"",
            Self::LessThanEquals => "\"<=\"",
            Self::LessThanLessThan => "\"<<\"",
            Self::Minus => "\"-\"",
            Self::MinusMinus => "\"--\"",
            Self::OpenBrace => "\"{\"",
            Self::OpenBracket => "\"[\"",
            Self::OpenParen => "\"(\"",
            Self::Percent => "\"%\"",
            Self::Plus => "\"+\"",
            Self::PlusPlus => "\"++\"",
            Self::Question => "\"?\"",
            Self::QuestionDot => "\"?.\"",
            Self::QuestionQuestion => "\"??\"",
            Self::Semicolon => "\";\"",
            Self::Slash => "\"/\"",
            Self::Tilde => "\"~\"",
            Self::AmpersandAmpersandEquals => "\"&&=\"",
            Self::AmpersandEquals => "\"&=\"",
            Self::AsteriskAsteriskEquals => "\"**=\"",
            Self::AsteriskEquals => "\"*=\"",
            Self::BarBarEquals => "\"||=\"",
            Self::BarEquals => "\"|=\"",
            Self::CaretEquals => "\"^=\"",
            Self::Equals => "\"=\"",
            Self::GreaterThanGreaterThanEquals => "\">>=\"",
            Self::GreaterThanGreaterThanGreaterThanEquals => "\">>>=\"",
            Self::LessThanLessThanEquals => "\"<<=\"",
            Self::MinusEquals => "\"-=\"",
            Self::PercentEquals => "\"%=\"",
            Self::PlusEquals => "\"+=\"",
            Self::QuestionQuestionEquals => "\"??=\"",
            Self::SlashEquals => "\"/=\"",
            Self::PrivateIdentifier => "private identifier",
            Self::Identifier => "identifier",
            Self::EscapedKeyword => "escaped keyword",
            Self::Break => "\"break\"",
            Self::Case => "\"case\"",
            Self::Catch => "\"catch\"",
            Self::Class => "\"class\"",
            Self::Const => "\"const\"",
            Self::Continue => "\"continue\"",
            Self::Debugger => "\"debugger\"",
            Self::Default => "\"default\"",
            Self::Delete => "\"delete\"",
            Self::Do => "\"do\"",
            Self::Else => "\"else\"",
            Self::Enum => "\"enum\"",
            Self::Export => "\"export\"",
            Self::Extends => "\"extends\"",
            Self::False => "\"false\"",
            Self::Finally => "\"finally\"",
            Self::For => "\"for\"",
            Self::Function => "\"function\"",
            Self::If => "\"if\"",
            Self::Import => "\"import\"",
            Self::In => "\"in\"",
            Self::Instanceof => "\"instanceof\"",
            Self::New => "\"new\"",
            Self::Null => "\"null\"",
            Self::Return => "\"return\"",
            Self::Super => "\"super\"",
            Self::Switch => "\"switch\"",
            Self::This => "\"this\"",
            Self::Throw => "\"throw\"",
            Self::True => "\"true\"",
            Self::Try => "\"try\"",
            Self::Typeof => "\"typeof\"",
            Self::Var => "\"var\"",
            Self::Void => "\"void\"",
            Self::While => "\"while\"",
            Self::With => "\"with\"",
        }
    }
}

#[must_use]
pub const fn token_to_string(token: Token) -> &'static str {
    token.as_str()
}

#[must_use]
pub fn keyword_token(text: &str) -> Option<Token> {
    Some(match text {
        "break" => Token::Break,
        "case" => Token::Case,
        "catch" => Token::Catch,
        "class" => Token::Class,
        "const" => Token::Const,
        "continue" => Token::Continue,
        "debugger" => Token::Debugger,
        "default" => Token::Default,
        "delete" => Token::Delete,
        "do" => Token::Do,
        "else" => Token::Else,
        "enum" => Token::Enum,
        "export" => Token::Export,
        "extends" => Token::Extends,
        "false" => Token::False,
        "finally" => Token::Finally,
        "for" => Token::For,
        "function" => Token::Function,
        "if" => Token::If,
        "import" => Token::Import,
        "in" => Token::In,
        "instanceof" => Token::Instanceof,
        "new" => Token::New,
        "null" => Token::Null,
        "return" => Token::Return,
        "super" => Token::Super,
        "switch" => Token::Switch,
        "this" => Token::This,
        "throw" => Token::Throw,
        "true" => Token::True,
        "try" => Token::Try,
        "typeof" => Token::Typeof,
        "var" => Token::Var,
        "void" => Token::Void,
        "while" => Token::While,
        "with" => Token::With,
        _ => return None,
    })
}

#[must_use]
pub fn jsx_entity(name: &str) -> Option<char> {
    Some(match name {
        "quot" => '\u{22}',
        "amp" => '\u{26}',
        "apos" => '\u{27}',
        "lt" => '\u{3C}',
        "gt" => '\u{3E}',
        "nbsp" => '\u{A0}',
        "iexcl" => '\u{A1}',
        "cent" => '\u{A2}',
        "pound" => '\u{A3}',
        "curren" => '\u{A4}',
        "yen" => '\u{A5}',
        "brvbar" => '\u{A6}',
        "sect" => '\u{A7}',
        "uml" => '\u{A8}',
        "copy" => '\u{A9}',
        "ordf" => '\u{AA}',
        "laquo" => '\u{AB}',
        "not" => '\u{AC}',
        "shy" => '\u{AD}',
        "reg" => '\u{AE}',
        "macr" => '\u{AF}',
        "deg" => '\u{B0}',
        "plusmn" => '\u{B1}',
        "sup2" => '\u{B2}',
        "sup3" => '\u{B3}',
        "acute" => '\u{B4}',
        "micro" => '\u{B5}',
        "para" => '\u{B6}',
        "middot" => '\u{B7}',
        "cedil" => '\u{B8}',
        "sup1" => '\u{B9}',
        "ordm" => '\u{BA}',
        "raquo" => '\u{BB}',
        "frac14" => '\u{BC}',
        "frac12" => '\u{BD}',
        "frac34" => '\u{BE}',
        "iquest" => '\u{BF}',
        "Agrave" => '\u{C0}',
        "Aacute" => '\u{C1}',
        "Acirc" => '\u{C2}',
        "Atilde" => '\u{C3}',
        "Auml" => '\u{C4}',
        "Aring" => '\u{C5}',
        "AElig" => '\u{C6}',
        "Ccedil" => '\u{C7}',
        "Egrave" => '\u{C8}',
        "Eacute" => '\u{C9}',
        "Ecirc" => '\u{CA}',
        "Euml" => '\u{CB}',
        "Igrave" => '\u{CC}',
        "Iacute" => '\u{CD}',
        "Icirc" => '\u{CE}',
        "Iuml" => '\u{CF}',
        "ETH" => '\u{D0}',
        "Ntilde" => '\u{D1}',
        "Ograve" => '\u{D2}',
        "Oacute" => '\u{D3}',
        "Ocirc" => '\u{D4}',
        "Otilde" => '\u{D5}',
        "Ouml" => '\u{D6}',
        "times" => '\u{D7}',
        "Oslash" => '\u{D8}',
        "Ugrave" => '\u{D9}',
        "Uacute" => '\u{DA}',
        "Ucirc" => '\u{DB}',
        "Uuml" => '\u{DC}',
        "Yacute" => '\u{DD}',
        "THORN" => '\u{DE}',
        "szlig" => '\u{DF}',
        "agrave" => '\u{E0}',
        "aacute" => '\u{E1}',
        "acirc" => '\u{E2}',
        "atilde" => '\u{E3}',
        "auml" => '\u{E4}',
        "aring" => '\u{E5}',
        "aelig" => '\u{E6}',
        "ccedil" => '\u{E7}',
        "egrave" => '\u{E8}',
        "eacute" => '\u{E9}',
        "ecirc" => '\u{EA}',
        "euml" => '\u{EB}',
        "igrave" => '\u{EC}',
        "iacute" => '\u{ED}',
        "icirc" => '\u{EE}',
        "iuml" => '\u{EF}',
        "eth" => '\u{F0}',
        "ntilde" => '\u{F1}',
        "ograve" => '\u{F2}',
        "oacute" => '\u{F3}',
        "ocirc" => '\u{F4}',
        "otilde" => '\u{F5}',
        "ouml" => '\u{F6}',
        "divide" => '\u{F7}',
        "oslash" => '\u{F8}',
        "ugrave" => '\u{F9}',
        "uacute" => '\u{FA}',
        "ucirc" => '\u{FB}',
        "uuml" => '\u{FC}',
        "yacute" => '\u{FD}',
        "thorn" => '\u{FE}',
        "yuml" => '\u{FF}',
        "OElig" => '\u{152}',
        "oelig" => '\u{153}',
        "Scaron" => '\u{160}',
        "scaron" => '\u{161}',
        "Yuml" => '\u{178}',
        "fnof" => '\u{192}',
        "circ" => '\u{2C6}',
        "tilde" => '\u{2DC}',
        "Alpha" => '\u{391}',
        "Beta" => '\u{392}',
        "Gamma" => '\u{393}',
        "Delta" => '\u{394}',
        "Epsilon" => '\u{395}',
        "Zeta" => '\u{396}',
        "Eta" => '\u{397}',
        "Theta" => '\u{398}',
        "Iota" => '\u{399}',
        "Kappa" => '\u{39A}',
        "Lambda" => '\u{39B}',
        "Mu" => '\u{39C}',
        "Nu" => '\u{39D}',
        "Xi" => '\u{39E}',
        "Omicron" => '\u{39F}',
        "Pi" => '\u{3A0}',
        "Rho" => '\u{3A1}',
        "Sigma" => '\u{3A3}',
        "Tau" => '\u{3A4}',
        "Upsilon" => '\u{3A5}',
        "Phi" => '\u{3A6}',
        "Chi" => '\u{3A7}',
        "Psi" => '\u{3A8}',
        "Omega" => '\u{3A9}',
        "alpha" => '\u{3B1}',
        "beta" => '\u{3B2}',
        "gamma" => '\u{3B3}',
        "delta" => '\u{3B4}',
        "epsilon" => '\u{3B5}',
        "zeta" => '\u{3B6}',
        "eta" => '\u{3B7}',
        "theta" => '\u{3B8}',
        "iota" => '\u{3B9}',
        "kappa" => '\u{3BA}',
        "lambda" => '\u{3BB}',
        "mu" => '\u{3BC}',
        "nu" => '\u{3BD}',
        "xi" => '\u{3BE}',
        "omicron" => '\u{3BF}',
        "pi" => '\u{3C0}',
        "rho" => '\u{3C1}',
        "sigmaf" => '\u{3C2}',
        "sigma" => '\u{3C3}',
        "tau" => '\u{3C4}',
        "upsilon" => '\u{3C5}',
        "phi" => '\u{3C6}',
        "chi" => '\u{3C7}',
        "psi" => '\u{3C8}',
        "omega" => '\u{3C9}',
        "thetasym" => '\u{3D1}',
        "upsih" => '\u{3D2}',
        "piv" => '\u{3D6}',
        "ensp" => '\u{2002}',
        "emsp" => '\u{2003}',
        "thinsp" => '\u{2009}',
        "zwnj" => '\u{200C}',
        "zwj" => '\u{200D}',
        "lrm" => '\u{200E}',
        "rlm" => '\u{200F}',
        "ndash" => '\u{2013}',
        "mdash" => '\u{2014}',
        "lsquo" => '\u{2018}',
        "rsquo" => '\u{2019}',
        "sbquo" => '\u{201A}',
        "ldquo" => '\u{201C}',
        "rdquo" => '\u{201D}',
        "bdquo" => '\u{201E}',
        "dagger" => '\u{2020}',
        "Dagger" => '\u{2021}',
        "bull" => '\u{2022}',
        "hellip" => '\u{2026}',
        "permil" => '\u{2030}',
        "prime" => '\u{2032}',
        "Prime" => '\u{2033}',
        "lsaquo" => '\u{2039}',
        "rsaquo" => '\u{203A}',
        "oline" => '\u{203E}',
        "frasl" => '\u{2044}',
        "euro" => '\u{20AC}',
        "image" => '\u{2111}',
        "weierp" => '\u{2118}',
        "real" => '\u{211C}',
        "trade" => '\u{2122}',
        "alefsym" => '\u{2135}',
        "larr" => '\u{2190}',
        "uarr" => '\u{2191}',
        "rarr" => '\u{2192}',
        "darr" => '\u{2193}',
        "harr" => '\u{2194}',
        "crarr" => '\u{21B5}',
        "lArr" => '\u{21D0}',
        "uArr" => '\u{21D1}',
        "rArr" => '\u{21D2}',
        "dArr" => '\u{21D3}',
        "hArr" => '\u{21D4}',
        "forall" => '\u{2200}',
        "part" => '\u{2202}',
        "exist" => '\u{2203}',
        "empty" => '\u{2205}',
        "nabla" => '\u{2207}',
        "isin" => '\u{2208}',
        "notin" => '\u{2209}',
        "ni" => '\u{220B}',
        "prod" => '\u{220F}',
        "sum" => '\u{2211}',
        "minus" => '\u{2212}',
        "lowast" => '\u{2217}',
        "radic" => '\u{221A}',
        "prop" => '\u{221D}',
        "infin" => '\u{221E}',
        "ang" => '\u{2220}',
        "and" => '\u{2227}',
        "or" => '\u{2228}',
        "cap" => '\u{2229}',
        "cup" => '\u{222A}',
        "int" => '\u{222B}',
        "there4" => '\u{2234}',
        "sim" => '\u{223C}',
        "cong" => '\u{2245}',
        "asymp" => '\u{2248}',
        "ne" => '\u{2260}',
        "equiv" => '\u{2261}',
        "le" => '\u{2264}',
        "ge" => '\u{2265}',
        "sub" => '\u{2282}',
        "sup" => '\u{2283}',
        "nsub" => '\u{2284}',
        "sube" => '\u{2286}',
        "supe" => '\u{2287}',
        "oplus" => '\u{2295}',
        "otimes" => '\u{2297}',
        "perp" => '\u{22A5}',
        "sdot" => '\u{22C5}',
        "lceil" => '\u{2308}',
        "rceil" => '\u{2309}',
        "lfloor" => '\u{230A}',
        "rfloor" => '\u{230B}',
        "lang" => '\u{2329}',
        "rang" => '\u{232A}',
        "loz" => '\u{25CA}',
        "spades" => '\u{2660}',
        "clubs" => '\u{2663}',
        "hearts" => '\u{2665}',
        "diams" => '\u{2666}',
        _ => return None,
    })
}

pub const TOKEN_COUNT: usize = 107;
pub const JSX_ENTITY_COUNT: usize = 253;
