// Generated from upstream internal/css_ast/css_decl_table.go.

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
#[repr(u16)]
pub enum Declaration {
    #[default]
    Unknown,
    AlignContent,
    AlignItems,
    AlignSelf,
    AlignmentBaseline,
    All,
    Animation,
    AnimationDelay,
    AnimationDirection,
    AnimationDuration,
    AnimationFillMode,
    AnimationIterationCount,
    AnimationName,
    AnimationPlayState,
    AnimationTimingFunction,
    Appearance,
    BackdropFilter,
    BackfaceVisibility,
    Background,
    BackgroundAttachment,
    BackgroundClip,
    BackgroundColor,
    BackgroundImage,
    BackgroundOrigin,
    BackgroundPosition,
    BackgroundPositionX,
    BackgroundPositionY,
    BackgroundRepeat,
    BackgroundSize,
    BaselineShift,
    BlockSize,
    Border,
    BorderBlockEnd,
    BorderBlockEndColor,
    BorderBlockEndStyle,
    BorderBlockEndWidth,
    BorderBlockStart,
    BorderBlockStartColor,
    BorderBlockStartStyle,
    BorderBlockStartWidth,
    BorderBottom,
    BorderBottomColor,
    BorderBottomLeftRadius,
    BorderBottomRightRadius,
    BorderBottomStyle,
    BorderBottomWidth,
    BorderCollapse,
    BorderColor,
    BorderImage,
    BorderImageOutset,
    BorderImageRepeat,
    BorderImageSlice,
    BorderImageSource,
    BorderImageWidth,
    BorderInlineEnd,
    BorderInlineEndColor,
    BorderInlineEndStyle,
    BorderInlineEndWidth,
    BorderInlineStart,
    BorderInlineStartColor,
    BorderInlineStartStyle,
    BorderInlineStartWidth,
    BorderLeft,
    BorderLeftColor,
    BorderLeftStyle,
    BorderLeftWidth,
    BorderRadius,
    BorderRight,
    BorderRightColor,
    BorderRightStyle,
    BorderRightWidth,
    BorderSpacing,
    BorderStyle,
    BorderTop,
    BorderTopColor,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderTopStyle,
    BorderTopWidth,
    BorderWidth,
    Bottom,
    BoxDecorationBreak,
    BoxShadow,
    BoxSizing,
    BreakAfter,
    BreakBefore,
    BreakInside,
    CaptionSide,
    CaretColor,
    Clear,
    Clip,
    ClipPath,
    ClipRule,
    Color,
    ColorInterpolation,
    ColorInterpolationFilters,
    ColumnCount,
    ColumnFill,
    ColumnGap,
    ColumnRule,
    ColumnRuleColor,
    ColumnRuleStyle,
    ColumnRuleWidth,
    ColumnSpan,
    ColumnWidth,
    Columns,
    Composes,
    Container,
    ContainerName,
    ContainerType,
    Content,
    CounterIncrement,
    CounterReset,
    CssFloat,
    CssText,
    Cursor,
    Direction,
    Display,
    DominantBaseline,
    EmptyCells,
    Fill,
    FillOpacity,
    FillRule,
    Filter,
    Flex,
    FlexBasis,
    FlexDirection,
    FlexFlow,
    FlexGrow,
    FlexShrink,
    FlexWrap,
    Float,
    FloodColor,
    FloodOpacity,
    Font,
    FontFamily,
    FontFeatureSettings,
    FontKerning,
    FontSize,
    FontSizeAdjust,
    FontStretch,
    FontStyle,
    FontSynthesis,
    FontVariant,
    FontVariantCaps,
    FontVariantEastAsian,
    FontVariantLigatures,
    FontVariantNumeric,
    FontVariantPosition,
    FontWeight,
    Gap,
    GlyphOrientationVertical,
    Grid,
    GridArea,
    GridAutoColumns,
    GridAutoFlow,
    GridAutoRows,
    GridColumn,
    GridColumnEnd,
    GridColumnGap,
    GridColumnStart,
    GridGap,
    GridRow,
    GridRowEnd,
    GridRowGap,
    GridRowStart,
    GridTemplate,
    GridTemplateAreas,
    GridTemplateColumns,
    GridTemplateRows,
    Height,
    Hyphens,
    ImageOrientation,
    ImageRendering,
    InitialLetter,
    InlineSize,
    Inset,
    JustifyContent,
    JustifyItems,
    JustifySelf,
    Left,
    LetterSpacing,
    LightingColor,
    LineBreak,
    LineHeight,
    ListStyle,
    ListStyleImage,
    ListStylePosition,
    ListStyleType,
    Margin,
    MarginBlockEnd,
    MarginBlockStart,
    MarginBottom,
    MarginInlineEnd,
    MarginInlineStart,
    MarginLeft,
    MarginRight,
    MarginTop,
    Marker,
    MarkerEnd,
    MarkerMid,
    MarkerStart,
    Mask,
    MaskComposite,
    MaskImage,
    MaskOrigin,
    MaskPosition,
    MaskRepeat,
    MaskSize,
    MaskType,
    MaxBlockSize,
    MaxHeight,
    MaxInlineSize,
    MaxWidth,
    MinBlockSize,
    MinHeight,
    MinInlineSize,
    MinWidth,
    ObjectFit,
    ObjectPosition,
    Opacity,
    Order,
    Orphans,
    Outline,
    OutlineColor,
    OutlineOffset,
    OutlineStyle,
    OutlineWidth,
    Overflow,
    OverflowAnchor,
    OverflowWrap,
    OverflowX,
    OverflowY,
    OverscrollBehavior,
    OverscrollBehaviorBlock,
    OverscrollBehaviorInline,
    OverscrollBehaviorX,
    OverscrollBehaviorY,
    Padding,
    PaddingBlockEnd,
    PaddingBlockStart,
    PaddingBottom,
    PaddingInlineEnd,
    PaddingInlineStart,
    PaddingLeft,
    PaddingRight,
    PaddingTop,
    PageBreakAfter,
    PageBreakBefore,
    PageBreakInside,
    PaintOrder,
    Perspective,
    PerspectiveOrigin,
    PlaceContent,
    PlaceItems,
    PlaceSelf,
    PointerEvents,
    Position,
    PrintColorAdjust,
    Quotes,
    Resize,
    Right,
    Rotate,
    RowGap,
    RubyAlign,
    RubyPosition,
    Scale,
    ScrollBehavior,
    ShapeRendering,
    StopColor,
    StopOpacity,
    Stroke,
    StrokeDasharray,
    StrokeDashoffset,
    StrokeLinecap,
    StrokeLinejoin,
    StrokeMiterlimit,
    StrokeOpacity,
    StrokeWidth,
    TabSize,
    TableLayout,
    TextAlign,
    TextAlignLast,
    TextAnchor,
    TextCombineUpright,
    TextDecoration,
    TextDecorationColor,
    TextDecorationLine,
    TextDecorationSkip,
    TextDecorationStyle,
    TextEmphasis,
    TextEmphasisColor,
    TextEmphasisPosition,
    TextEmphasisStyle,
    TextIndent,
    TextJustify,
    TextOrientation,
    TextOverflow,
    TextRendering,
    TextShadow,
    TextSizeAdjust,
    TextTransform,
    TextUnderlinePosition,
    Top,
    TouchAction,
    Transform,
    TransformBox,
    TransformOrigin,
    TransformStyle,
    Transition,
    TransitionDelay,
    TransitionDuration,
    TransitionProperty,
    TransitionTimingFunction,
    Translate,
    UnicodeBidi,
    UserSelect,
    VerticalAlign,
    Visibility,
    WhiteSpace,
    Widows,
    Width,
    WillChange,
    WordBreak,
    WordSpacing,
    WordWrap,
    WritingMode,
    ZIndex,
    Zoom,
}

pub(super) const KNOWN_DECLARATION_PAIRS: &[(&str, Declaration)] = &[
    ("align-content", Declaration::AlignContent),
    ("align-items", Declaration::AlignItems),
    ("align-self", Declaration::AlignSelf),
    ("alignment-baseline", Declaration::AlignmentBaseline),
    ("all", Declaration::All),
    ("animation", Declaration::Animation),
    ("animation-delay", Declaration::AnimationDelay),
    ("animation-direction", Declaration::AnimationDirection),
    ("animation-duration", Declaration::AnimationDuration),
    ("animation-fill-mode", Declaration::AnimationFillMode),
    (
        "animation-iteration-count",
        Declaration::AnimationIterationCount,
    ),
    ("animation-name", Declaration::AnimationName),
    ("animation-play-state", Declaration::AnimationPlayState),
    (
        "animation-timing-function",
        Declaration::AnimationTimingFunction,
    ),
    ("appearance", Declaration::Appearance),
    ("backdrop-filter", Declaration::BackdropFilter),
    ("backface-visibility", Declaration::BackfaceVisibility),
    ("background", Declaration::Background),
    ("background-attachment", Declaration::BackgroundAttachment),
    ("background-clip", Declaration::BackgroundClip),
    ("background-color", Declaration::BackgroundColor),
    ("background-image", Declaration::BackgroundImage),
    ("background-origin", Declaration::BackgroundOrigin),
    ("background-position", Declaration::BackgroundPosition),
    ("background-position-x", Declaration::BackgroundPositionX),
    ("background-position-y", Declaration::BackgroundPositionY),
    ("background-repeat", Declaration::BackgroundRepeat),
    ("background-size", Declaration::BackgroundSize),
    ("baseline-shift", Declaration::BaselineShift),
    ("block-size", Declaration::BlockSize),
    ("border", Declaration::Border),
    ("border-block-end", Declaration::BorderBlockEnd),
    ("border-block-end-color", Declaration::BorderBlockEndColor),
    ("border-block-end-style", Declaration::BorderBlockEndStyle),
    ("border-block-end-width", Declaration::BorderBlockEndWidth),
    ("border-block-start", Declaration::BorderBlockStart),
    (
        "border-block-start-color",
        Declaration::BorderBlockStartColor,
    ),
    (
        "border-block-start-style",
        Declaration::BorderBlockStartStyle,
    ),
    (
        "border-block-start-width",
        Declaration::BorderBlockStartWidth,
    ),
    ("border-bottom", Declaration::BorderBottom),
    ("border-bottom-color", Declaration::BorderBottomColor),
    (
        "border-bottom-left-radius",
        Declaration::BorderBottomLeftRadius,
    ),
    (
        "border-bottom-right-radius",
        Declaration::BorderBottomRightRadius,
    ),
    ("border-bottom-style", Declaration::BorderBottomStyle),
    ("border-bottom-width", Declaration::BorderBottomWidth),
    ("border-collapse", Declaration::BorderCollapse),
    ("border-color", Declaration::BorderColor),
    ("border-image", Declaration::BorderImage),
    ("border-image-outset", Declaration::BorderImageOutset),
    ("border-image-repeat", Declaration::BorderImageRepeat),
    ("border-image-slice", Declaration::BorderImageSlice),
    ("border-image-source", Declaration::BorderImageSource),
    ("border-image-width", Declaration::BorderImageWidth),
    ("border-inline-end", Declaration::BorderInlineEnd),
    ("border-inline-end-color", Declaration::BorderInlineEndColor),
    ("border-inline-end-style", Declaration::BorderInlineEndStyle),
    ("border-inline-end-width", Declaration::BorderInlineEndWidth),
    ("border-inline-start", Declaration::BorderInlineStart),
    (
        "border-inline-start-color",
        Declaration::BorderInlineStartColor,
    ),
    (
        "border-inline-start-style",
        Declaration::BorderInlineStartStyle,
    ),
    (
        "border-inline-start-width",
        Declaration::BorderInlineStartWidth,
    ),
    ("border-left", Declaration::BorderLeft),
    ("border-left-color", Declaration::BorderLeftColor),
    ("border-left-style", Declaration::BorderLeftStyle),
    ("border-left-width", Declaration::BorderLeftWidth),
    ("border-radius", Declaration::BorderRadius),
    ("border-right", Declaration::BorderRight),
    ("border-right-color", Declaration::BorderRightColor),
    ("border-right-style", Declaration::BorderRightStyle),
    ("border-right-width", Declaration::BorderRightWidth),
    ("border-spacing", Declaration::BorderSpacing),
    ("border-style", Declaration::BorderStyle),
    ("border-top", Declaration::BorderTop),
    ("border-top-color", Declaration::BorderTopColor),
    ("border-top-left-radius", Declaration::BorderTopLeftRadius),
    ("border-top-right-radius", Declaration::BorderTopRightRadius),
    ("border-top-style", Declaration::BorderTopStyle),
    ("border-top-width", Declaration::BorderTopWidth),
    ("border-width", Declaration::BorderWidth),
    ("bottom", Declaration::Bottom),
    ("box-decoration-break", Declaration::BoxDecorationBreak),
    ("box-shadow", Declaration::BoxShadow),
    ("box-sizing", Declaration::BoxSizing),
    ("break-after", Declaration::BreakAfter),
    ("break-before", Declaration::BreakBefore),
    ("break-inside", Declaration::BreakInside),
    ("caption-side", Declaration::CaptionSide),
    ("caret-color", Declaration::CaretColor),
    ("clear", Declaration::Clear),
    ("clip", Declaration::Clip),
    ("clip-path", Declaration::ClipPath),
    ("clip-rule", Declaration::ClipRule),
    ("color", Declaration::Color),
    ("color-interpolation", Declaration::ColorInterpolation),
    (
        "color-interpolation-filters",
        Declaration::ColorInterpolationFilters,
    ),
    ("column-count", Declaration::ColumnCount),
    ("column-fill", Declaration::ColumnFill),
    ("column-gap", Declaration::ColumnGap),
    ("column-rule", Declaration::ColumnRule),
    ("column-rule-color", Declaration::ColumnRuleColor),
    ("column-rule-style", Declaration::ColumnRuleStyle),
    ("column-rule-width", Declaration::ColumnRuleWidth),
    ("column-span", Declaration::ColumnSpan),
    ("column-width", Declaration::ColumnWidth),
    ("columns", Declaration::Columns),
    ("composes", Declaration::Composes),
    ("container", Declaration::Container),
    ("container-name", Declaration::ContainerName),
    ("container-type", Declaration::ContainerType),
    ("content", Declaration::Content),
    ("counter-increment", Declaration::CounterIncrement),
    ("counter-reset", Declaration::CounterReset),
    ("css-float", Declaration::CssFloat),
    ("css-text", Declaration::CssText),
    ("cursor", Declaration::Cursor),
    ("direction", Declaration::Direction),
    ("display", Declaration::Display),
    ("dominant-baseline", Declaration::DominantBaseline),
    ("empty-cells", Declaration::EmptyCells),
    ("fill", Declaration::Fill),
    ("fill-opacity", Declaration::FillOpacity),
    ("fill-rule", Declaration::FillRule),
    ("filter", Declaration::Filter),
    ("flex", Declaration::Flex),
    ("flex-basis", Declaration::FlexBasis),
    ("flex-direction", Declaration::FlexDirection),
    ("flex-flow", Declaration::FlexFlow),
    ("flex-grow", Declaration::FlexGrow),
    ("flex-shrink", Declaration::FlexShrink),
    ("flex-wrap", Declaration::FlexWrap),
    ("float", Declaration::Float),
    ("flood-color", Declaration::FloodColor),
    ("flood-opacity", Declaration::FloodOpacity),
    ("font", Declaration::Font),
    ("font-family", Declaration::FontFamily),
    ("font-feature-settings", Declaration::FontFeatureSettings),
    ("font-kerning", Declaration::FontKerning),
    ("font-size", Declaration::FontSize),
    ("font-size-adjust", Declaration::FontSizeAdjust),
    ("font-stretch", Declaration::FontStretch),
    ("font-style", Declaration::FontStyle),
    ("font-synthesis", Declaration::FontSynthesis),
    ("font-variant", Declaration::FontVariant),
    ("font-variant-caps", Declaration::FontVariantCaps),
    ("font-variant-east-asian", Declaration::FontVariantEastAsian),
    ("font-variant-ligatures", Declaration::FontVariantLigatures),
    ("font-variant-numeric", Declaration::FontVariantNumeric),
    ("font-variant-position", Declaration::FontVariantPosition),
    ("font-weight", Declaration::FontWeight),
    ("gap", Declaration::Gap),
    (
        "glyph-orientation-vertical",
        Declaration::GlyphOrientationVertical,
    ),
    ("grid", Declaration::Grid),
    ("grid-area", Declaration::GridArea),
    ("grid-auto-columns", Declaration::GridAutoColumns),
    ("grid-auto-flow", Declaration::GridAutoFlow),
    ("grid-auto-rows", Declaration::GridAutoRows),
    ("grid-column", Declaration::GridColumn),
    ("grid-column-end", Declaration::GridColumnEnd),
    ("grid-column-gap", Declaration::GridColumnGap),
    ("grid-column-start", Declaration::GridColumnStart),
    ("grid-gap", Declaration::GridGap),
    ("grid-row", Declaration::GridRow),
    ("grid-row-end", Declaration::GridRowEnd),
    ("grid-row-gap", Declaration::GridRowGap),
    ("grid-row-start", Declaration::GridRowStart),
    ("grid-template", Declaration::GridTemplate),
    ("grid-template-areas", Declaration::GridTemplateAreas),
    ("grid-template-columns", Declaration::GridTemplateColumns),
    ("grid-template-rows", Declaration::GridTemplateRows),
    ("height", Declaration::Height),
    ("hyphens", Declaration::Hyphens),
    ("image-orientation", Declaration::ImageOrientation),
    ("image-rendering", Declaration::ImageRendering),
    ("initial-letter", Declaration::InitialLetter),
    ("inline-size", Declaration::InlineSize),
    ("inset", Declaration::Inset),
    ("justify-content", Declaration::JustifyContent),
    ("justify-items", Declaration::JustifyItems),
    ("justify-self", Declaration::JustifySelf),
    ("left", Declaration::Left),
    ("letter-spacing", Declaration::LetterSpacing),
    ("lighting-color", Declaration::LightingColor),
    ("line-break", Declaration::LineBreak),
    ("line-height", Declaration::LineHeight),
    ("list-style", Declaration::ListStyle),
    ("list-style-image", Declaration::ListStyleImage),
    ("list-style-position", Declaration::ListStylePosition),
    ("list-style-type", Declaration::ListStyleType),
    ("margin", Declaration::Margin),
    ("margin-block-end", Declaration::MarginBlockEnd),
    ("margin-block-start", Declaration::MarginBlockStart),
    ("margin-bottom", Declaration::MarginBottom),
    ("margin-inline-end", Declaration::MarginInlineEnd),
    ("margin-inline-start", Declaration::MarginInlineStart),
    ("margin-left", Declaration::MarginLeft),
    ("margin-right", Declaration::MarginRight),
    ("margin-top", Declaration::MarginTop),
    ("marker", Declaration::Marker),
    ("marker-end", Declaration::MarkerEnd),
    ("marker-mid", Declaration::MarkerMid),
    ("marker-start", Declaration::MarkerStart),
    ("mask", Declaration::Mask),
    ("mask-composite", Declaration::MaskComposite),
    ("mask-image", Declaration::MaskImage),
    ("mask-origin", Declaration::MaskOrigin),
    ("mask-position", Declaration::MaskPosition),
    ("mask-repeat", Declaration::MaskRepeat),
    ("mask-size", Declaration::MaskSize),
    ("mask-type", Declaration::MaskType),
    ("max-block-size", Declaration::MaxBlockSize),
    ("max-height", Declaration::MaxHeight),
    ("max-inline-size", Declaration::MaxInlineSize),
    ("max-width", Declaration::MaxWidth),
    ("min-block-size", Declaration::MinBlockSize),
    ("min-height", Declaration::MinHeight),
    ("min-inline-size", Declaration::MinInlineSize),
    ("min-width", Declaration::MinWidth),
    ("object-fit", Declaration::ObjectFit),
    ("object-position", Declaration::ObjectPosition),
    ("opacity", Declaration::Opacity),
    ("order", Declaration::Order),
    ("orphans", Declaration::Orphans),
    ("outline", Declaration::Outline),
    ("outline-color", Declaration::OutlineColor),
    ("outline-offset", Declaration::OutlineOffset),
    ("outline-style", Declaration::OutlineStyle),
    ("outline-width", Declaration::OutlineWidth),
    ("overflow", Declaration::Overflow),
    ("overflow-anchor", Declaration::OverflowAnchor),
    ("overflow-wrap", Declaration::OverflowWrap),
    ("overflow-x", Declaration::OverflowX),
    ("overflow-y", Declaration::OverflowY),
    ("overscroll-behavior", Declaration::OverscrollBehavior),
    (
        "overscroll-behavior-block",
        Declaration::OverscrollBehaviorBlock,
    ),
    (
        "overscroll-behavior-inline",
        Declaration::OverscrollBehaviorInline,
    ),
    ("overscroll-behavior-x", Declaration::OverscrollBehaviorX),
    ("overscroll-behavior-y", Declaration::OverscrollBehaviorY),
    ("padding", Declaration::Padding),
    ("padding-block-end", Declaration::PaddingBlockEnd),
    ("padding-block-start", Declaration::PaddingBlockStart),
    ("padding-bottom", Declaration::PaddingBottom),
    ("padding-inline-end", Declaration::PaddingInlineEnd),
    ("padding-inline-start", Declaration::PaddingInlineStart),
    ("padding-left", Declaration::PaddingLeft),
    ("padding-right", Declaration::PaddingRight),
    ("padding-top", Declaration::PaddingTop),
    ("page-break-after", Declaration::PageBreakAfter),
    ("page-break-before", Declaration::PageBreakBefore),
    ("page-break-inside", Declaration::PageBreakInside),
    ("paint-order", Declaration::PaintOrder),
    ("perspective", Declaration::Perspective),
    ("perspective-origin", Declaration::PerspectiveOrigin),
    ("place-content", Declaration::PlaceContent),
    ("place-items", Declaration::PlaceItems),
    ("place-self", Declaration::PlaceSelf),
    ("pointer-events", Declaration::PointerEvents),
    ("position", Declaration::Position),
    ("print-color-adjust", Declaration::PrintColorAdjust),
    ("quotes", Declaration::Quotes),
    ("resize", Declaration::Resize),
    ("right", Declaration::Right),
    ("rotate", Declaration::Rotate),
    ("row-gap", Declaration::RowGap),
    ("ruby-align", Declaration::RubyAlign),
    ("ruby-position", Declaration::RubyPosition),
    ("scale", Declaration::Scale),
    ("scroll-behavior", Declaration::ScrollBehavior),
    ("shape-rendering", Declaration::ShapeRendering),
    ("stop-color", Declaration::StopColor),
    ("stop-opacity", Declaration::StopOpacity),
    ("stroke", Declaration::Stroke),
    ("stroke-dasharray", Declaration::StrokeDasharray),
    ("stroke-dashoffset", Declaration::StrokeDashoffset),
    ("stroke-linecap", Declaration::StrokeLinecap),
    ("stroke-linejoin", Declaration::StrokeLinejoin),
    ("stroke-miterlimit", Declaration::StrokeMiterlimit),
    ("stroke-opacity", Declaration::StrokeOpacity),
    ("stroke-width", Declaration::StrokeWidth),
    ("tab-size", Declaration::TabSize),
    ("table-layout", Declaration::TableLayout),
    ("text-align", Declaration::TextAlign),
    ("text-align-last", Declaration::TextAlignLast),
    ("text-anchor", Declaration::TextAnchor),
    ("text-combine-upright", Declaration::TextCombineUpright),
    ("text-decoration", Declaration::TextDecoration),
    ("text-decoration-color", Declaration::TextDecorationColor),
    ("text-decoration-line", Declaration::TextDecorationLine),
    ("text-decoration-skip", Declaration::TextDecorationSkip),
    ("text-decoration-style", Declaration::TextDecorationStyle),
    ("text-emphasis", Declaration::TextEmphasis),
    ("text-emphasis-color", Declaration::TextEmphasisColor),
    ("text-emphasis-position", Declaration::TextEmphasisPosition),
    ("text-emphasis-style", Declaration::TextEmphasisStyle),
    ("text-indent", Declaration::TextIndent),
    ("text-justify", Declaration::TextJustify),
    ("text-orientation", Declaration::TextOrientation),
    ("text-overflow", Declaration::TextOverflow),
    ("text-rendering", Declaration::TextRendering),
    ("text-shadow", Declaration::TextShadow),
    ("text-size-adjust", Declaration::TextSizeAdjust),
    ("text-transform", Declaration::TextTransform),
    (
        "text-underline-position",
        Declaration::TextUnderlinePosition,
    ),
    ("top", Declaration::Top),
    ("touch-action", Declaration::TouchAction),
    ("transform", Declaration::Transform),
    ("transform-box", Declaration::TransformBox),
    ("transform-origin", Declaration::TransformOrigin),
    ("transform-style", Declaration::TransformStyle),
    ("transition", Declaration::Transition),
    ("transition-delay", Declaration::TransitionDelay),
    ("transition-duration", Declaration::TransitionDuration),
    ("transition-property", Declaration::TransitionProperty),
    (
        "transition-timing-function",
        Declaration::TransitionTimingFunction,
    ),
    ("translate", Declaration::Translate),
    ("unicode-bidi", Declaration::UnicodeBidi),
    ("user-select", Declaration::UserSelect),
    ("vertical-align", Declaration::VerticalAlign),
    ("visibility", Declaration::Visibility),
    ("white-space", Declaration::WhiteSpace),
    ("widows", Declaration::Widows),
    ("width", Declaration::Width),
    ("will-change", Declaration::WillChange),
    ("word-break", Declaration::WordBreak),
    ("word-spacing", Declaration::WordSpacing),
    ("word-wrap", Declaration::WordWrap),
    ("writing-mode", Declaration::WritingMode),
    ("z-index", Declaration::ZIndex),
    ("zoom", Declaration::Zoom),
];
